# SITE CONFIGURATION
baseurl: ""
url: "https://im-coder-lg.github.io"

# THEME-SPECIFIC CONFIGURATION
title: LG's blog                              # site's title
description: "<code>hello there</code>"      # used by search engines
avatar: assets/img/triangle.png                         # Empty for no avatar in navbar
favicon: assets/favicon.ico                             # Icon displayed in the tab

# Header and footer text
header_text: my blog.  # Change Blog header text
header_feature_image: assets/img/pexels/triangular.jpeg
footer_text: >
  Powered by <a href="https://jekyllrb.com/">Jekyll</a> with <a href="https://github.com/sylhare/Type-on-Strap">Type on Strap</a>

# Blog
excerpt: true                                           # Or "truncate" (first 250 characters), "false" to disable
post_navigation: true
color_image: /assets/img/lineart.png                    # A bit transparent for color posts.

# Features
# More in the _data folder for share buttons, author and language
# For layout customization, go to the "_sass > base" folder, and check "_variables.scss"
katex: true                                             # Enable if using math markup
mermaid: true                                           # Enable mermaid-js for sequence and diagrams
google_analytics:                                       # Tracking ID, e.g. "UA-000000-01"
cookie_consent: true                                   # To respect the usage of cookies
color_theme: auto                                       # auto, dark or light

# Comments
comments:
  disqus_shortname:                                     # Your discus shortname for comments
  cusdis_app_id:                                        # Your cusdis data-app-id
  utterances:                                           # Enable by filling below information. For more info, go to https://utteranc.es
    repo: im-coder-lg/my-blog-comments                                              # your public comments repository (e.g. owner/repo)
    issue-term: title                                        # Issue term (e.g. "comment" consider issues with this word in the title as comments)
    theme: github-dark
    label: mainblogcomment

# PAGINATION
paginate: 5
paginate_path: "/blog/page:num"

# PORTFOLIO
collections:
  portfolio:
    output: true
    permalink: /:collection/:name

# BUILD SETTINGS
sass:
  style: compressed
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-feed]
exclude: [".jekyll-cache", ".idea", "vendor/*", "assets/node_modules/*"]

# theme: type-on-strap                                  # if using the theme as a jekyll theme gem
remote_theme: sylhare/Type-on-Strap                     # If using as a remote_theme in github
